import postgres from 'postgres';
import { createHash, randomBytes, randomUUID } from 'crypto';
import {
  Article,
  ArticleStatus,
  EditRequest,
  EditRequestStatus,
  Profile,
  UserRole,
  generateSlug,
  isValidSlug,
  normalizeTags,
  parseSearchQuery,
  sanitizeMarkdown,
  sanitizeEmail,
  sanitizeRole,
  sanitizeText,
  sanitizeThemeColor,
  sanitizeUsername,
  searchArticles
} from './utils';

type MemoryStore = {
  articles: Article[];
  profiles: Profile[];
  likes: Set<string>;
  editRequests: EditRequest[];
  users: UserRecord[];
};

type UserRecord = {
  id: string;
  username: string;
  email: string;
  passwordHash: string;
  provider: string;
  providerAccountId: string;
  emailVerified: boolean;
  verificationTokenHash: string;
  verificationTokenExpiresAt: string | null;
  verificationTokenUsedAt: string | null;
  createdAt: string;
  updatedAt: string;
};

type ArticleInput = {
  title: string;
  content: string;
  tags: string[];
  authorUsername: string;
};

const MAX_TITLE_LENGTH = 140;

const PHASE_7_SEED_ARTICLES: Array<Pick<ArticleInput, 'title' | 'content' | 'tags'> & { slug: string }> = [
  {
    slug: 'the-industrial-revolution',
    title: 'The Industrial Revolution',
    tags: ['history', 'technology', 'economics', 'civilization'],
    content: `# The Industrial Revolution

The Industrial Revolution was a period of far-reaching economic and social change that began in Britain in the late eighteenth century and expanded through Europe and North America during the nineteenth century. It shifted production from handcraft systems to mechanized factory systems and transformed transport, labor, and daily life.

## Origins In Britain

Several conditions made Britain an early center of industrialization: accessible coal deposits, established trade networks, political stability, and capital generated by commercial expansion. Textile manufacturing was a leading sector, especially after inventions such as the spinning jenny, water frame, and power loom accelerated output.

## Steam, Iron, And Railways

Steam power, refined by engineers including James Watt, became central to industry and transportation. Iron production expanded through new smelting methods, and railways connected industrial cities to ports and mining regions. This reduced transport costs and allowed goods, people, and ideas to move faster than in previous centuries.

## Social Effects

Industrialization increased total output and wealth, but benefits were uneven. Urban populations grew rapidly, often in unhealthy housing conditions near factories. Workers, including women and children, could face long hours and dangerous environments. Over time, labor organizing and reform laws pushed for safer conditions, limits on child labor, and broader political representation.

## Global Influence

The Industrial Revolution reshaped global power balances by strengthening states that industrialized quickly. It also accelerated imperial extraction and international trade networks. Its long-term legacy includes modern manufacturing, mass transportation, and the energy-intensive economic systems that still influence climate and development debates.

## Related Topics

- The Renaissance and scientific inquiry
- The Internet and communication infrastructure
- The Cold War and twentieth-century industrial strategy`
  },
  {
    slug: 'ancient-rome',
    title: 'Ancient Rome',
    tags: ['history', 'civilization', 'politics', 'war'],
    content: `# Ancient Rome

Ancient Rome developed from a city-state in central Italy into one of the most influential civilizations in world history. Across centuries, Rome moved through monarchy, republic, and imperial rule while shaping law, governance, engineering, and military institutions across the Mediterranean.

## Republic And Expansion

After the traditional end of monarchy, Roman elites organized a republic with elected magistrates and a senate. The republic expanded through alliances and wars, including conflicts with Carthage in the Punic Wars. Military success brought territory and wealth but also intensified political competition and social tension within Rome.

## From Republic To Empire

By the first century BCE, civil conflicts weakened republican structures. Julius Caesar's rise, assassination, and the power struggle that followed culminated in Octavian's victory and the establishment of imperial rule as Augustus. The empire later reached vast territorial scale, integrating diverse peoples under Roman administration.

## Law, Infrastructure, And Culture

Roman legal principles influenced later legal systems in Europe and beyond. Roads, aqueducts, and urban planning demonstrated durable engineering methods. Latin language and Roman literary culture spread through administration and education, leaving long-lasting effects on vocabulary, law, and scholarship.

## Transformation And Legacy

The Western Roman Empire declined through a combination of political instability, military pressure, and economic strain, while the Eastern Roman (Byzantine) Empire continued for centuries. Rome's institutions and cultural memory influenced Renaissance political thought, modern republican ideals, and historical writing.

## Related Topics

- The Renaissance and revival of classical learning
- World War II and uses of Roman symbolism in modern politics
- The Cold War and debates over empire and state power`
  },
  {
    slug: 'world-war-ii',
    title: 'World War II',
    tags: ['history', 'war', 'politics', 'technology'],
    content: `# World War II

World War II lasted from 1939 to 1945 and involved major powers across Europe, Asia, Africa, and the Pacific. It began after Nazi Germany invaded Poland and expanded into a conflict defined by total war, industrial mobilization, mass civilian targeting, and genocide.

## Major Theaters

In Europe, Germany achieved rapid early victories before being pushed back by the Soviet Union, Allied campaigns in Italy and France, and strategic bombing. In Asia and the Pacific, imperial Japan expanded aggressively before reversals in battles such as Midway and later Allied advances toward Japan.

## The Holocaust

The Holocaust was the systematic persecution and murder of six million Jews by Nazi Germany and its collaborators, alongside mass killings of Roma, disabled people, political prisoners, and others. It remains central to understanding the war's moral and historical consequences.

## Industry, Science, And Strategy

Industrial capacity and logistics were decisive. Radar, codebreaking, long-range aviation, and mechanized warfare altered military planning. The war ended in Europe in May 1945 and in Asia in August 1945 after atomic bombings of Hiroshima and Nagasaki and Soviet entry into the Pacific war.

## Aftermath

World War II reshaped international institutions and geopolitics. The United Nations was founded, decolonization accelerated, and rivalry between the United States and Soviet Union hardened into the Cold War.

## Related Topics

- The Cold War and postwar blocs
- Space Exploration and rocket technology origins
- The Internet and military research networks`
  },
  {
    slug: 'the-renaissance',
    title: 'The Renaissance',
    tags: ['history', 'culture', 'civilization', 'technology'],
    content: `# The Renaissance

The Renaissance was a broad cultural movement that began in Italian city-states in the fourteenth century and later spread across Europe. It emphasized humanistic learning, close study of classical texts, and new approaches to art, science, and political thought.

## Humanism And Learning

Humanist scholars recovered and interpreted Greek and Roman works in language, philosophy, and history. Their methods encouraged critical reading, rhetorical training, and historical comparison. Printing technology increased the circulation of books and ideas, creating wider intellectual networks.

## Art And Scientific Observation

Renaissance artists developed new techniques in perspective, anatomy, and composition. Figures such as Leonardo da Vinci and Michelangelo connected artistic practice with close observation of nature and the human body. Scientific inquiry expanded through experimentation and mathematical description.

## Politics And Institutions

Powerful city-states and courts sponsored scholarship and the arts while competing for prestige. Diplomatic practices, statecraft writing, and administrative reforms evolved in tandem with cultural change. Renaissance ideas later influenced educational institutions and early modern political theory.

## Long-Term Significance

The Renaissance did not replace medieval culture in a single break, but it helped reshape European intellectual life and contributed to later scientific and technological transformations, including those associated with industrialization.

## Related Topics

- Ancient Rome and classical inheritance
- The Industrial Revolution and mechanized modernity
- The Internet and new knowledge networks`
  },
  {
    slug: 'the-cold-war',
    title: 'The Cold War',
    tags: ['history', 'war', 'politics', 'technology'],
    content: `# The Cold War

The Cold War was a prolonged geopolitical conflict between the United States and the Soviet Union, usually dated from the late 1940s to 1991. It involved ideological rivalry, military alliances, proxy wars, arms competition, and technological contest without direct full-scale war between the two superpowers.

## Bloc Formation

After World War II, Europe was divided into Western and Eastern spheres, institutionalized through NATO and the Warsaw Pact. Economic programs, intelligence networks, and media campaigns reinforced this divide.

## Crises And Proxy Conflicts

Major flashpoints included Berlin confrontations, the Korean War, the Cuban Missile Crisis, the Vietnam War, and conflicts in Afghanistan, Africa, and Latin America. These events showed how regional wars could become global strategic contests.

## Arms And Technology

Nuclear deterrence shaped strategy, producing doctrines such as mutually assured destruction. The space race and computing research became symbols of national capability. Many technologies later used in civilian life were accelerated by Cold War funding priorities.

## End Of The Cold War

Economic strain, political reform in the Soviet Union, and popular movements in Eastern Europe transformed the geopolitical landscape. The Soviet Union dissolved in 1991, ending bipolar superpower rivalry while leaving unresolved security and ideological legacies.

## Related Topics

- World War II and postwar settlement
- Space Exploration and superpower competition
- The Internet and defense research origins`
  },
  {
    slug: 'the-internet',
    title: 'The Internet',
    tags: ['technology', 'history', 'communication', 'science'],
    content: `# The Internet

The Internet is a global network of networks that enables digital communication, information exchange, and distributed computing at planetary scale. It emerged through decades of research in packet switching, networking protocols, and computing infrastructure.

## Early Development

Research programs in the United States and Europe developed packet-switched networking in the 1960s and 1970s. ARPANET demonstrated practical long-distance computer networking, while later protocol work established TCP/IP as a shared standard.

## Expansion And The Web

In the 1990s, the World Wide Web, web browsers, and commercial internet service providers made networked information widely accessible. Email, search engines, and online publishing transformed communication, education, and business.

## Social And Economic Impact

The Internet reshaped media, labor, politics, and social life. It enabled rapid collaboration and innovation but also introduced challenges involving privacy, misinformation, platform concentration, and cybersecurity.

## Infrastructure And Governance

Internet operation relies on physical infrastructure, standards bodies, and policy coordination across governments and private organizations. Debates over regulation, open access, and digital rights continue to define its future.

## Related Topics

- The Industrial Revolution and infrastructure transitions
- The Cold War and early networking research
- Space Exploration and global communication systems`
  },
  {
    slug: 'space-exploration',
    title: 'Space Exploration',
    tags: ['science', 'technology', 'history', 'war'],
    content: `# Space Exploration

Space exploration is the investigation of outer space through astronomy, robotic missions, and human spaceflight. It grew rapidly in the twentieth century, especially during Cold War competition, and now includes both national programs and private-sector initiatives.

## Early Milestones

The launch of Sputnik in 1957 began the space age. Yuri Gagarin became the first human in orbit in 1961, and Apollo 11 landed humans on the Moon in 1969. These achievements required advances in propulsion, guidance, materials, and systems engineering.

## Robotic Science Missions

Robotic probes expanded knowledge of the solar system by visiting planets, moons, and asteroids. Space telescopes and observatories provided high-precision data about cosmic structure, planetary climates, and stellar evolution.

## International Cooperation

The International Space Station demonstrated long-term cooperation in human spaceflight and research. Shared projects and data exchange continue across agencies, universities, and industry.

## New Era

Reusable launch systems lowered some costs and increased launch frequency. Current priorities include lunar return missions, Mars planning, Earth-observation satellites, and planetary defense initiatives.

## Related Topics

- The Cold War and geopolitical competition
- World War II and rocket technology foundations
- The Internet and satellite communication networks`
  }
];

declare global {
  // eslint-disable-next-line no-var
  var __miniWikiMemory__: MemoryStore | undefined;
}

const DATABASE_URL = process.env.DATABASE_URL || '';
const useMemory = !DATABASE_URL;

const memory: MemoryStore =
  globalThis.__miniWikiMemory__ ||
  (globalThis.__miniWikiMemory__ = {
    articles: [],
    profiles: [],
    likes: new Set<string>(),
    editRequests: [],
    users: []
  });

const sql = useMemory
  ? null
  : postgres(DATABASE_URL, {
      ssl: 'require',
      max: 5,
      idle_timeout: 20,
      connect_timeout: 20
    });

let initialized = false;
const EMAIL_VERIFICATION_TTL_MS = 1000 * 60 * 60 * 24;

function defaultRoleFor(username: string): UserRole {
  if (username === 'guest') return 'guest';
  return username === 'admin' ? 'admin' : 'user';
}

function canDirectEdit(role: UserRole): boolean {
  return role === 'editor' || role === 'admin';
}

function canModerate(role: UserRole): boolean {
  return role === 'admin';
}

function canPublish(role: UserRole): boolean {
  return role === 'user' || canDirectEdit(role);
}

function canRequestEdits(role: UserRole): boolean {
  return role === 'user';
}

function getVerificationSecret(): string {
  return sanitizeText(process.env.NEXTAUTH_SECRET || process.env.AUTH_SECRET || 'miniwiki-dev-secret', 256) || 'miniwiki-dev-secret';
}

function hashVerificationToken(token: string): string {
  return createHash('sha256')
    .update(`${getVerificationSecret()}:${sanitizeText(token, 512)}`)
    .digest('hex');
}

function isVisible(article: Article, requester: string, role: UserRole): boolean {
  if (article.status === 'published') return true;
  if (canDirectEdit(role)) return true;
  return article.authorUsername === requester;
}

function mapArticle(row: any): Article {
  return {
    id: row.id,
    slug: row.slug,
    title: row.title,
    content: row.content,
    tags: Array.isArray(row.tags) ? row.tags : [],
    authorUsername: row.author_username,
    status: (row.status || 'published') as ArticleStatus,
    likes: Number(row.likes || 0),
    views: Number(row.views || 0),
    createdAt: row.created_at,
    updatedAt: row.updated_at
  };
}

function mapProfile(row: any): Profile {
  return {
    username: row.username,
    themeColor: row.theme_color,
    role: sanitizeRole(row.role || defaultRoleFor(row.username)),
    updatedAt: row.updated_at
  };
}

function mapEditRequest(row: any): EditRequest {
  return {
    id: row.id,
    articleSlug: row.article_slug,
    requesterUsername: row.requester_username,
    intent: row.intent,
    proposedTitle: row.proposed_title || '',
    proposedContent: row.proposed_content || '',
    proposedTags: Array.isArray(row.proposed_tags) ? row.proposed_tags : [],
    status: (row.status || 'pending') as EditRequestStatus,
    reviewedBy: row.reviewed_by || '',
    createdAt: row.created_at,
    updatedAt: row.updated_at
  };
}

function mapUser(row: any): UserRecord {
  return {
    id: row.id,
    username: row.username,
    email: row.email,
    passwordHash: row.password_hash || '',
    provider: row.provider || 'credentials',
    providerAccountId: row.provider_account_id || '',
    emailVerified: Boolean(row.email_verified),
    verificationTokenHash: row.verification_token_hash || '',
    verificationTokenExpiresAt: row.verification_token_expires_at ? new Date(row.verification_token_expires_at).toISOString() : null,
    verificationTokenUsedAt: row.verification_token_used_at ? new Date(row.verification_token_used_at).toISOString() : null,
    createdAt: row.created_at,
    updatedAt: row.updated_at
  };
}

async function seedMemoryIfNeeded(): Promise<void> {
  if (memory.articles.length > 0) return;
  const now = new Date().toISOString();

  memory.profiles.push({
    username: 'admin',
    themeColor: '#2563eb',
    role: 'admin',
    updatedAt: now
  });

  memory.articles = PHASE_7_SEED_ARTICLES.map((seed, index) => ({
    id: randomUUID(),
    slug: seed.slug,
    title: sanitizeText(seed.title, MAX_TITLE_LENGTH),
    content: sanitizeMarkdown(seed.content),
    tags: normalizeTags(seed.tags),
    authorUsername: 'system',
    status: 'published',
    likes: 10 - index,
    views: 100 + index * 20,
    createdAt: now,
    updatedAt: now
  }));
}

async function seedPostgresIfNeeded(): Promise<void> {
  const countRows = await sql!`SELECT COUNT(*)::INT AS count FROM articles`;
  const count = Number(countRows[0]?.count || 0);
  if (count > 0) return;

  for (const seed of PHASE_7_SEED_ARTICLES) {
    const title = sanitizeText(seed.title, MAX_TITLE_LENGTH);
    const content = sanitizeMarkdown(seed.content);
    const tags = normalizeTags(seed.tags);
    const now = new Date().toISOString();

    await sql!`
      INSERT INTO articles (id, slug, title, content, tags, author_username, status, likes, views, created_at, updated_at)
      VALUES (${randomUUID()}, ${seed.slug}, ${title}, ${content}, ${tags}, ${'system'}, ${'published'}, ${6}, ${120}, ${now}, ${now})
      ON CONFLICT (slug) DO NOTHING
    `;
  }

  await sql!`
    INSERT INTO profiles (username, theme_color, role)
    VALUES (${`admin`}, ${`#2563eb`}, ${`admin`})
    ON CONFLICT (username) DO NOTHING
  `;
}

async function ensureProfileExists(username: string): Promise<Profile> {
  const safeUser = sanitizeUsername(username);
  const existing = await getProfile(safeUser);
  if (existing) return existing;
  return upsertProfile(safeUser, '#2563eb');
}

export async function getRoleForUsername(username: string): Promise<UserRole> {
  const safeUser = sanitizeUsername(username);
  if (!safeUser || safeUser === 'guest') return 'guest';

  const profile = await ensureProfileExists(safeUser);
  return profile.role;
}

export async function canUserEditDirectly(username: string): Promise<boolean> {
  const role = await getRoleForUsername(username);
  return canDirectEdit(role);
}

export async function ensureDbInitialized(): Promise<void> {
  if (initialized) return;

  if (useMemory) {
    await seedMemoryIfNeeded();
    initialized = true;
    return;
  }

  await sql!`CREATE TABLE IF NOT EXISTS profiles (
    username TEXT PRIMARY KEY,
    theme_color TEXT NOT NULL DEFAULT '#2563eb',
    role TEXT NOT NULL DEFAULT 'user',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`;

  await sql!`ALTER TABLE profiles ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'user'`;

  await sql!`CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL DEFAULT '',
    provider TEXT NOT NULL DEFAULT 'credentials',
    provider_account_id TEXT NOT NULL DEFAULT '',
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    verification_token_hash TEXT NOT NULL DEFAULT '',
    verification_token_expires_at TIMESTAMPTZ,
    verification_token_used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`;

  await sql!`ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified BOOLEAN NOT NULL DEFAULT FALSE`;
  await sql!`ALTER TABLE users ADD COLUMN IF NOT EXISTS verification_token_hash TEXT NOT NULL DEFAULT ''`;
  await sql!`ALTER TABLE users ADD COLUMN IF NOT EXISTS verification_token_expires_at TIMESTAMPTZ`;
  await sql!`ALTER TABLE users ADD COLUMN IF NOT EXISTS verification_token_used_at TIMESTAMPTZ`;

  await sql!`CREATE TABLE IF NOT EXISTS articles (
    id TEXT PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    tags TEXT[] NOT NULL DEFAULT '{}',
    author_username TEXT NOT NULL DEFAULT 'anonymous',
    status TEXT NOT NULL DEFAULT 'published',
    likes INTEGER NOT NULL DEFAULT 0,
    views INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`;

  await sql!`ALTER TABLE articles ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'published'`;

  await sql!`CREATE TABLE IF NOT EXISTS article_likes (
    article_slug TEXT NOT NULL,
    username TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (article_slug, username)
  )`;

  await sql!`CREATE TABLE IF NOT EXISTS edit_requests (
    id TEXT PRIMARY KEY,
    article_slug TEXT NOT NULL,
    requester_username TEXT NOT NULL,
    intent TEXT NOT NULL DEFAULT '',
    proposed_title TEXT NOT NULL DEFAULT '',
    proposed_content TEXT NOT NULL DEFAULT '',
    proposed_tags TEXT[] NOT NULL DEFAULT '{}',
    status TEXT NOT NULL DEFAULT 'pending',
    reviewed_by TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`;

  await sql!`CREATE INDEX IF NOT EXISTS idx_articles_updated_at ON articles(updated_at DESC)`;
  await sql!`CREATE INDEX IF NOT EXISTS idx_articles_title ON articles(title)`;
  await sql!`CREATE INDEX IF NOT EXISTS idx_articles_tags ON articles USING GIN(tags)`;
  await sql!`CREATE INDEX IF NOT EXISTS idx_articles_status ON articles(status)`;
  await sql!`CREATE INDEX IF NOT EXISTS idx_edit_requests_article_slug ON edit_requests(article_slug)`;
  await sql!`CREATE INDEX IF NOT EXISTS idx_edit_requests_status ON edit_requests(status)`;
  await sql!`CREATE INDEX IF NOT EXISTS idx_users_email ON users(email)`;
  await sql!`CREATE INDEX IF NOT EXISTS idx_users_username ON users(username)`;
  await sql!`CREATE INDEX IF NOT EXISTS idx_users_verification_token_hash ON users(verification_token_hash)`;

  await seedPostgresIfNeeded();

  initialized = true;
}

export async function listArticles(search = '', requesterUsername = 'guest'): Promise<Article[]> {
  await ensureDbInitialized();

  const requester = sanitizeUsername(requesterUsername);
  const role = await getRoleForUsername(requester);
  const parsed = parseSearchQuery(search);

  if (useMemory) {
    const visible = memory.articles.filter((article) => isVisible(article, requester, role));
    return searchArticles(visible, parsed.normalized);
  }

  const rows = await sql!`SELECT * FROM articles ORDER BY updated_at DESC`;
  const mapped = rows.map(mapArticle).filter((article) => isVisible(article, requester, role));

  if (parsed.mode === 'empty') return mapped;
  return searchArticles(mapped, parsed.normalized);
}

export async function getArticleBySlug(slug: string, requesterUsername = 'guest'): Promise<Article | null> {
  await ensureDbInitialized();
  if (!isValidSlug(slug)) return null;

  const requester = sanitizeUsername(requesterUsername);
  const role = await getRoleForUsername(requester);

  if (useMemory) {
    const found = memory.articles.find((article) => article.slug === slug) || null;
    if (!found) return null;
    return isVisible(found, requester, role) ? found : null;
  }

  const rows = await sql!`SELECT * FROM articles WHERE slug = ${slug} LIMIT 1`;
  if (rows.length === 0) return null;

  const article = mapArticle(rows[0]);
  return isVisible(article, requester, role) ? article : null;
}

export async function createArticle(payload: ArticleInput): Promise<Article> {
  await ensureDbInitialized();

  const title = sanitizeText(payload.title, MAX_TITLE_LENGTH);
  const content = sanitizeMarkdown(payload.content);
  const tags = normalizeTags(payload.tags);
  const author = sanitizeUsername(payload.authorUsername);
  const role = await getRoleForUsername(author);
  if (!canPublish(role)) {
    throw new Error('Verify your email before creating articles.');
  }
  const status: ArticleStatus = canDirectEdit(role) ? 'published' : 'pending';

  const baseSlug = generateSlug(title);
  let slug = baseSlug;
  let suffix = 1;

  const slugExists = async (value: string) => {
    if (useMemory) {
      return memory.articles.some((article) => article.slug === value);
    }
    const rows = await sql!`SELECT slug FROM articles WHERE slug = ${value} LIMIT 1`;
    return rows.length > 0;
  };

  while (await slugExists(slug)) {
    suffix += 1;
    slug = `${baseSlug}-${suffix}`;
  }

  const id = randomUUID();
  const now = new Date().toISOString();

  if (useMemory) {
    const created: Article = {
      id,
      slug,
      title,
      content,
      tags,
      authorUsername: author,
      status,
      likes: 0,
      views: 0,
      createdAt: now,
      updatedAt: now
    };
    memory.articles.unshift(created);
    return created;
  }

  const rows = await sql!`
    INSERT INTO articles (id, slug, title, content, tags, author_username, status)
    VALUES (${id}, ${slug}, ${title}, ${content}, ${tags}, ${author}, ${status})
    RETURNING *
  `;

  return mapArticle(rows[0]);
}

export async function updateArticle(
  slug: string,
  payload: { title: string; content: string; tags: string[]; editorUsername: string }
): Promise<Article | null> {
  await ensureDbInitialized();
  if (!isValidSlug(slug)) return null;

  const editor = sanitizeUsername(payload.editorUsername);
  const role = await getRoleForUsername(editor);
  if (!canDirectEdit(role)) return null;

  const title = sanitizeText(payload.title, MAX_TITLE_LENGTH);
  const content = sanitizeMarkdown(payload.content);
  const tags = normalizeTags(payload.tags);

  if (useMemory) {
    const index = memory.articles.findIndex((article) => article.slug === slug);
    if (index === -1) return null;

    const updated: Article = {
      ...memory.articles[index],
      title,
      content,
      tags,
      status: 'published',
      updatedAt: new Date().toISOString()
    };
    memory.articles[index] = updated;
    return updated;
  }

  const rows = await sql!`
    UPDATE articles
    SET title = ${title},
        content = ${content},
        tags = ${tags},
        status = ${'published'},
        updated_at = NOW()
    WHERE slug = ${slug}
    RETURNING *
  `;

  if (rows.length === 0) return null;
  return mapArticle(rows[0]);
}

export async function deleteArticle(slug: string, actorUsername: string): Promise<boolean> {
  await ensureDbInitialized();
  if (!isValidSlug(slug)) return false;

  const actor = sanitizeUsername(actorUsername);
  const role = await getRoleForUsername(actor);

  if (useMemory) {
    const before = memory.articles.length;
    memory.articles = memory.articles.filter((article) => {
      if (article.slug !== slug) return true;
      if (role === 'admin') return false;
      return article.authorUsername !== actor;
    });

    memory.likes.forEach((value) => {
      if (value.startsWith(`${slug}::`)) memory.likes.delete(value);
    });

    memory.editRequests = memory.editRequests.filter((request) => request.articleSlug !== slug);
    return memory.articles.length < before;
  }

  await sql!`DELETE FROM article_likes WHERE article_slug = ${slug}`;
  await sql!`DELETE FROM edit_requests WHERE article_slug = ${slug}`;

  if (role === 'admin') {
    const result = await sql!`DELETE FROM articles WHERE slug = ${slug}`;
    return result.count > 0;
  }

  const result = await sql!`DELETE FROM articles WHERE slug = ${slug} AND author_username = ${actor}`;
  return result.count > 0;
}

export async function incrementView(slug: string, requesterUsername = 'guest'): Promise<Article | null> {
  await ensureDbInitialized();
  if (!isValidSlug(slug)) return null;

  const found = await getArticleBySlug(slug, requesterUsername);
  if (!found) return null;

  if (useMemory) {
    const index = memory.articles.findIndex((article) => article.slug === slug);
    if (index === -1) return null;

    memory.articles[index] = {
      ...memory.articles[index],
      views: memory.articles[index].views + 1,
      updatedAt: new Date().toISOString()
    };
    return memory.articles[index];
  }

  const rows = await sql!`
    UPDATE articles
    SET views = views + 1,
        updated_at = NOW()
    WHERE slug = ${slug}
    RETURNING *
  `;

  if (rows.length === 0) return null;
  return mapArticle(rows[0]);
}

export async function likeArticle(slug: string, username: string): Promise<Article | null> {
  await ensureDbInitialized();
  if (!isValidSlug(slug)) return null;

  const safeUser = sanitizeUsername(username);
  if (!safeUser || safeUser === 'guest') return null;

  const found = await getArticleBySlug(slug, safeUser);
  if (!found) return null;

  if (useMemory) {
    const index = memory.articles.findIndex((article) => article.slug === slug);
    if (index === -1) return null;

    memory.likes.add(`${slug}::${safeUser}`);
    const likeCount = [...memory.likes].filter((value) => value.startsWith(`${slug}::`)).length;

    memory.articles[index] = {
      ...memory.articles[index],
      likes: likeCount,
      updatedAt: new Date().toISOString()
    };
    return memory.articles[index];
  }

  await sql!`
    INSERT INTO article_likes (article_slug, username)
    VALUES (${slug}, ${safeUser})
    ON CONFLICT DO NOTHING
  `;

  const rows = await sql!`
    UPDATE articles a
    SET likes = (
      SELECT COUNT(*)::INT FROM article_likes l WHERE l.article_slug = a.slug
    )
    WHERE a.slug = ${slug}
    RETURNING *
  `;

  if (rows.length === 0) return null;
  return mapArticle(rows[0]);
}

export async function submitEditRequest(payload: {
  slug: string;
  requesterUsername: string;
  intent: string;
  proposedTitle?: string;
  proposedContent?: string;
  proposedTags?: string[];
}): Promise<EditRequest | null> {
  await ensureDbInitialized();

  const slug = sanitizeText(payload.slug, 180);
  if (!isValidSlug(slug)) return null;

  const requester = sanitizeUsername(payload.requesterUsername);
  if (!requester || requester === 'guest') return null;

  const role = await getRoleForUsername(requester);
  if (role === 'pending') return null;
  if (canDirectEdit(role)) return null;
  if (!canRequestEdits(role)) return null;

  const article = await getArticleBySlug(slug, requester);
  if (!article) return null;

  const intent = sanitizeText(payload.intent, 400);
  const proposedTitle = sanitizeText(payload.proposedTitle || '', MAX_TITLE_LENGTH);
  const proposedContent = sanitizeMarkdown(payload.proposedContent || '');
  const proposedTags = normalizeTags(payload.proposedTags || []);
  const hasProposedChanges = Boolean(proposedTitle || proposedContent.trim() || proposedTags.length > 0);

  if (intent.length < 8 && !hasProposedChanges) {
    return null;
  }

  const now = new Date().toISOString();
  const request: EditRequest = {
    id: randomUUID(),
    articleSlug: slug,
    requesterUsername: requester,
    intent,
    proposedTitle,
    proposedContent,
    proposedTags,
    status: 'pending',
    reviewedBy: '',
    createdAt: now,
    updatedAt: now
  };

  if (useMemory) {
    memory.editRequests.unshift(request);
    return request;
  }

  const rows = await sql!`
    INSERT INTO edit_requests (id, article_slug, requester_username, intent, proposed_title, proposed_content, proposed_tags, status, reviewed_by)
    VALUES (${request.id}, ${slug}, ${requester}, ${intent}, ${proposedTitle}, ${proposedContent}, ${proposedTags}, ${'pending'}, ${''})
    RETURNING *
  `;

  return mapEditRequest(rows[0]);
}

export async function listEditRequestsForArticle(slug: string, actorUsername: string): Promise<EditRequest[]> {
  await ensureDbInitialized();
  if (!isValidSlug(slug)) return [];

  const role = await getRoleForUsername(actorUsername);
  if (!canModerate(role)) return [];

  if (useMemory) {
    return memory.editRequests.filter((request) => request.articleSlug === slug).sort((a, b) => b.createdAt.localeCompare(a.createdAt));
  }

  const rows = await sql!`SELECT * FROM edit_requests WHERE article_slug = ${slug} ORDER BY created_at DESC`;
  return rows.map(mapEditRequest);
}

export async function reviewEditRequest(payload: {
  requestId: string;
  actorUsername: string;
  decision: 'approved' | 'rejected';
}): Promise<EditRequest | null> {
  await ensureDbInitialized();

  const actor = sanitizeUsername(payload.actorUsername);
  const role = await getRoleForUsername(actor);
  if (!canModerate(role)) return null;

  const decision: EditRequestStatus = payload.decision === 'approved' ? 'approved' : 'rejected';

  if (useMemory) {
    const index = memory.editRequests.findIndex((request) => request.id === payload.requestId);
    if (index === -1) return null;

    const current = memory.editRequests[index];
    const updatedRequest: EditRequest = {
      ...current,
      status: decision,
      reviewedBy: actor,
      updatedAt: new Date().toISOString()
    };
    memory.editRequests[index] = updatedRequest;

    if (decision === 'approved') {
      const articleIndex = memory.articles.findIndex((article) => article.slug === current.articleSlug);
      if (articleIndex >= 0) {
        memory.articles[articleIndex] = {
          ...memory.articles[articleIndex],
          title: current.proposedTitle || memory.articles[articleIndex].title,
          content: current.proposedContent || memory.articles[articleIndex].content,
          tags: current.proposedTags.length > 0 ? current.proposedTags : memory.articles[articleIndex].tags,
          status: 'published',
          updatedAt: new Date().toISOString()
        };
      }
    }

    return updatedRequest;
  }

  const rows = await sql!`SELECT * FROM edit_requests WHERE id = ${payload.requestId} LIMIT 1`;
  if (rows.length === 0) return null;
  const current = mapEditRequest(rows[0]);

  const updatedRows = await sql!`
    UPDATE edit_requests
    SET status = ${decision},
        reviewed_by = ${actor},
        updated_at = NOW()
    WHERE id = ${payload.requestId}
    RETURNING *
  `;

  if (decision === 'approved') {
    const sourceRows = await sql!`SELECT * FROM articles WHERE slug = ${current.articleSlug} LIMIT 1`;
    if (sourceRows.length > 0) {
      const source = mapArticle(sourceRows[0]);
      const nextTitle = current.proposedTitle || source.title;
      const nextContent = current.proposedContent || source.content;
      const nextTags = current.proposedTags.length > 0 ? current.proposedTags : source.tags;

      await sql!`
        UPDATE articles
        SET title = ${nextTitle},
            content = ${nextContent},
            tags = ${nextTags},
            status = ${'published'},
            updated_at = NOW()
        WHERE slug = ${current.articleSlug}
      `;
    }
  }

  return updatedRows.length > 0 ? mapEditRequest(updatedRows[0]) : null;
}

export async function reviewArticle(payload: {
  slug: string;
  actorUsername: string;
  decision: 'approved' | 'rejected';
}): Promise<Article | null> {
  await ensureDbInitialized();
  if (!isValidSlug(payload.slug)) return null;

  const actor = sanitizeUsername(payload.actorUsername);
  const role = await getRoleForUsername(actor);
  if (!canModerate(role)) return null;

  const status: ArticleStatus = payload.decision === 'approved' ? 'published' : 'rejected';

  if (useMemory) {
    const index = memory.articles.findIndex((article) => article.slug === payload.slug);
    if (index === -1) return null;

    memory.articles[index] = {
      ...memory.articles[index],
      status,
      updatedAt: new Date().toISOString()
    };
    return memory.articles[index];
  }

  const rows = await sql!`
    UPDATE articles
    SET status = ${status},
        updated_at = NOW()
    WHERE slug = ${payload.slug}
    RETURNING *
  `;

  if (rows.length === 0) return null;
  return mapArticle(rows[0]);
}

export async function getProfile(username: string): Promise<Profile | null> {
  await ensureDbInitialized();
  const safeUser = sanitizeUsername(username);
  if (!safeUser || safeUser === 'guest') return null;

  if (useMemory) {
    return memory.profiles.find((profile) => profile.username === safeUser) || null;
  }

  const rows = await sql!`SELECT * FROM profiles WHERE username = ${safeUser} LIMIT 1`;
  if (rows.length === 0) return null;
  return mapProfile(rows[0]);
}

export async function upsertProfile(username: string, themeColor: string, roleOverride?: UserRole): Promise<Profile> {
  await ensureDbInitialized();
  const safeUser = sanitizeUsername(username);
  const safeColor = sanitizeThemeColor(themeColor);

  if (useMemory) {
    const index = memory.profiles.findIndex((profile) => profile.username === safeUser);
    const existingRole =
      roleOverride || (safeUser === 'guest' ? 'guest' : index === -1 ? defaultRoleFor(safeUser) : memory.profiles[index].role);

    const profile: Profile = {
      username: safeUser,
      themeColor: safeColor,
      role: existingRole,
      updatedAt: new Date().toISOString()
    };

    if (index === -1) {
      memory.profiles.push(profile);
    } else {
      memory.profiles[index] = profile;
    }
    return profile;
  }

  const existing = await sql!`SELECT * FROM profiles WHERE username = ${safeUser} LIMIT 1`;
  const role = roleOverride || (safeUser === 'guest' ? 'guest' : existing.length > 0 ? sanitizeRole(existing[0].role) : defaultRoleFor(safeUser));

  const rows = await sql!`
    INSERT INTO profiles (username, theme_color, role)
    VALUES (${safeUser}, ${safeColor}, ${role})
    ON CONFLICT (username)
    DO UPDATE SET
      theme_color = EXCLUDED.theme_color,
      role = COALESCE(${roleOverride || null}, profiles.role),
      updated_at = NOW()
    RETURNING *
  `;

  return mapProfile(rows[0]);
}

function buildUsernameFromSeed(seed: string): string {
  const sanitized = sanitizeUsername(seed);
  if (!sanitized || sanitized === 'guest') {
    return `user-${Date.now().toString().slice(-6)}`;
  }
  return sanitized;
}

async function usernameExists(username: string): Promise<boolean> {
  if (useMemory) {
    return memory.users.some((user) => user.username === username);
  }
  const rows = await sql!`SELECT id FROM users WHERE username = ${username} LIMIT 1`;
  return rows.length > 0;
}

async function buildUniqueUsername(seed: string): Promise<string> {
  const base = buildUsernameFromSeed(seed);
  let candidate = base;
  let suffix = 1;

  while (await usernameExists(candidate)) {
    suffix += 1;
    candidate = `${base}-${suffix}`;
  }

  return candidate;
}

export async function getAuthUserById(id: string): Promise<UserRecord | null> {
  await ensureDbInitialized();
  const safeId = sanitizeText(id, 120);
  if (!safeId) return null;

  if (useMemory) {
    return memory.users.find((user) => user.id === safeId) || null;
  }

  const rows = await sql!`SELECT * FROM users WHERE id = ${safeId} LIMIT 1`;
  if (rows.length === 0) return null;
  return mapUser(rows[0]);
}

export async function getAuthUserByIdentifier(identifier: string): Promise<UserRecord | null> {
  await ensureDbInitialized();
  const safeIdentifier = sanitizeText(identifier, 254).toLowerCase();
  if (!safeIdentifier) return null;

  if (useMemory) {
    return (
      memory.users.find(
        (user) => user.username.toLowerCase() === safeIdentifier || user.email.toLowerCase() === safeIdentifier
      ) || null
    );
  }

  const rows = await sql!`
    SELECT * FROM users
    WHERE LOWER(username) = ${safeIdentifier} OR LOWER(email) = ${safeIdentifier}
    LIMIT 1
  `;
  if (rows.length === 0) return null;
  return mapUser(rows[0]);
}

export async function getAuthUserByEmail(email: string): Promise<UserRecord | null> {
  await ensureDbInitialized();
  const safeEmail = sanitizeEmail(email);
  if (!safeEmail) return null;

  if (useMemory) {
    return memory.users.find((user) => user.email === safeEmail) || null;
  }

  const rows = await sql!`SELECT * FROM users WHERE email = ${safeEmail} LIMIT 1`;
  if (rows.length === 0) return null;
  return mapUser(rows[0]);
}

export async function issueEmailVerificationToken(
  userId: string
): Promise<{ email: string; username: string; token: string; expiresAt: string } | null> {
  await ensureDbInitialized();
  const user = await getAuthUserById(userId);
  if (!user) return null;

  const token = randomBytes(32).toString('base64url');
  const tokenHash = hashVerificationToken(token);
  const expiresAt = new Date(Date.now() + EMAIL_VERIFICATION_TTL_MS).toISOString();

  if (useMemory) {
    const index = memory.users.findIndex((entry) => entry.id === user.id);
    if (index === -1) return null;

    memory.users[index] = {
      ...memory.users[index],
      verificationTokenHash: tokenHash,
      verificationTokenExpiresAt: expiresAt,
      verificationTokenUsedAt: null,
      updatedAt: new Date().toISOString()
    };
  } else {
    await sql!`
      UPDATE users
      SET verification_token_hash = ${tokenHash},
          verification_token_expires_at = ${expiresAt},
          verification_token_used_at = ${null},
          updated_at = NOW()
      WHERE id = ${user.id}
    `;
  }

  return {
    email: user.email,
    username: user.username,
    token,
    expiresAt
  };
}

export async function verifyEmailVerificationToken(
  token: string
): Promise<{ username: string; email: string; role: UserRole } | null> {
  await ensureDbInitialized();
  const safeToken = sanitizeText(token, 512);
  if (!safeToken) return null;

  const tokenHash = hashVerificationToken(safeToken);
  const now = new Date();
  let user: UserRecord | null = null;

  if (useMemory) {
    user =
      memory.users.find((entry) => {
        if (entry.emailVerified) return false;
        if (!entry.verificationTokenHash || entry.verificationTokenHash !== tokenHash) return false;
        if (entry.verificationTokenUsedAt) return false;
        if (!entry.verificationTokenExpiresAt) return false;
        return new Date(entry.verificationTokenExpiresAt).getTime() > now.getTime();
      }) || null;

    if (!user) return null;

    const index = memory.users.findIndex((entry) => entry.id === user!.id);
    const verifiedAt = now.toISOString();
    memory.users[index] = {
      ...memory.users[index],
      emailVerified: true,
      verificationTokenHash: '',
      verificationTokenExpiresAt: null,
      verificationTokenUsedAt: verifiedAt,
      updatedAt: verifiedAt
    };
    user = memory.users[index];
  } else {
    const rows = await sql!`
      SELECT * FROM users
      WHERE verification_token_hash = ${tokenHash}
        AND email_verified = FALSE
        AND verification_token_used_at IS NULL
        AND verification_token_expires_at IS NOT NULL
        AND verification_token_expires_at > NOW()
      LIMIT 1
    `;
    if (rows.length === 0) return null;

    const verifiedRows = await sql!`
      UPDATE users
      SET email_verified = ${true},
          verification_token_hash = ${''},
          verification_token_expires_at = ${null},
          verification_token_used_at = NOW(),
          updated_at = NOW()
      WHERE id = ${rows[0].id}
      RETURNING *
    `;
    user = verifiedRows.length > 0 ? mapUser(verifiedRows[0]) : null;
  }

  if (!user) return null;

  const currentProfile = await getProfile(user.username);
  const nextRole = currentProfile?.role === 'editor' || currentProfile?.role === 'admin' ? currentProfile.role : 'user';
  const profile = await upsertProfile(user.username, currentProfile?.themeColor || '#2563eb', nextRole);

  return {
    username: user.username,
    email: user.email,
    role: profile.role
  };
}

export async function createAuthUser(payload: {
  username: string;
  email: string;
  passwordHash?: string;
  provider?: string;
  providerAccountId?: string;
  emailVerified?: boolean;
  role?: UserRole;
}): Promise<{ id: string; username: string; email: string; role: UserRole } | null> {
  await ensureDbInitialized();

  const safeEmail = sanitizeEmail(payload.email);
  if (!safeEmail) return null;

  const existingByEmail = await getAuthUserByEmail(safeEmail);
  if (existingByEmail) return null;

  const username = await buildUniqueUsername(payload.username || safeEmail.split('@')[0] || 'user');
  const id = randomUUID();
  const now = new Date().toISOString();
  const passwordHash = sanitizeText(payload.passwordHash || '', 255);
  const provider = sanitizeText(payload.provider || 'credentials', 32) || 'credentials';
  const providerAccountId = sanitizeText(payload.providerAccountId || '', 120);
  const initialRole = sanitizeRole(payload.role || (payload.emailVerified ? 'user' : 'pending'));
  const emailVerified = Boolean(payload.emailVerified);

  if (useMemory) {
    memory.users.push({
      id,
      username,
      email: safeEmail,
      passwordHash,
      provider,
      providerAccountId,
      emailVerified,
      verificationTokenHash: '',
      verificationTokenExpiresAt: null,
      verificationTokenUsedAt: null,
      createdAt: now,
      updatedAt: now
    });
  } else {
    await sql!`
      INSERT INTO users (
        id,
        username,
        email,
        password_hash,
        provider,
        provider_account_id,
        email_verified,
        verification_token_hash,
        verification_token_expires_at,
        verification_token_used_at,
        created_at,
        updated_at
      )
      VALUES (
        ${id},
        ${username},
        ${safeEmail},
        ${passwordHash},
        ${provider},
        ${providerAccountId},
        ${emailVerified},
        ${''},
        ${null},
        ${null},
        ${now},
        ${now}
      )
    `;
  }

  const profile = await upsertProfile(username, '#2563eb', initialRole);
  return { id, username, email: safeEmail, role: profile.role };
}

export async function upsertGoogleAuthUser(payload: {
  email: string;
  name?: string;
  providerAccountId: string;
}): Promise<{ id: string; username: string; email: string; role: UserRole } | null> {
  await ensureDbInitialized();

  const safeEmail = sanitizeEmail(payload.email);
  const googleId = sanitizeText(payload.providerAccountId, 120);
  if (!safeEmail || !googleId) return null;

  const existing = await getAuthUserByEmail(safeEmail);
  if (existing) {
    if (useMemory) {
      const index = memory.users.findIndex((user) => user.id === existing.id);
      if (index >= 0) {
        memory.users[index] = {
          ...memory.users[index],
          provider: 'google',
          providerAccountId: googleId,
          emailVerified: true,
          verificationTokenHash: '',
          verificationTokenExpiresAt: null,
          verificationTokenUsedAt: null,
          updatedAt: new Date().toISOString()
        };
      }
    } else {
      await sql!`
        UPDATE users
        SET provider = ${'google'},
            provider_account_id = ${googleId},
            email_verified = ${true},
            verification_token_hash = ${''},
            verification_token_expires_at = ${null},
            verification_token_used_at = ${null},
            updated_at = NOW()
        WHERE id = ${existing.id}
      `;
    }

    const currentProfile = await getProfile(existing.username);
    const currentRole = await getRoleForUsername(existing.username);
    const profile = await upsertProfile(
      existing.username,
      currentProfile?.themeColor || '#2563eb',
      currentRole === 'pending' ? 'user' : currentRole
    );
    return { id: existing.id, username: existing.username, email: existing.email, role: profile.role };
  }

  return createAuthUser({
    username: payload.name || safeEmail.split('@')[0] || 'user',
    email: safeEmail,
    provider: 'google',
    providerAccountId: googleId,
    emailVerified: true,
    role: 'user'
  });
}

export async function setUserRole(payload: {
  targetUsername: string;
  actorUsername: string;
  role: UserRole;
}): Promise<Profile | null> {
  await ensureDbInitialized();

  const actor = sanitizeUsername(payload.actorUsername);
  const actorRole = await getRoleForUsername(actor);
  if (!canModerate(actorRole)) return null;

  const target = sanitizeUsername(payload.targetUsername);
  const nextRole: UserRole = payload.role === 'admin' || payload.role === 'editor' || payload.role === 'user' ? payload.role : 'user';

  if (!target || target === 'guest') return null;

  if (useMemory) {
    const index = memory.profiles.findIndex((profile) => profile.username === target);
    const now = new Date().toISOString();

    if (index === -1) {
      const profile: Profile = {
        username: target,
        themeColor: '#2563eb',
        role: nextRole,
        updatedAt: now
      };
      memory.profiles.push(profile);
      return profile;
    }

    memory.profiles[index] = {
      ...memory.profiles[index],
      role: nextRole,
      updatedAt: now
    };
    return memory.profiles[index];
  }

  const existing = await sql!`SELECT * FROM profiles WHERE username = ${target} LIMIT 1`;
  const themeColor = existing.length > 0 ? sanitizeThemeColor(existing[0].theme_color) : '#2563eb';

  const rows = await sql!`
    INSERT INTO profiles (username, theme_color, role)
    VALUES (${target}, ${themeColor}, ${nextRole})
    ON CONFLICT (username)
    DO UPDATE SET role = EXCLUDED.role, updated_at = NOW()
    RETURNING *
  `;

  return mapProfile(rows[0]);
}
